
import React from 'react';
import { Result, Question } from '../types';
import { Trophy, RefreshCcw, AlertCircle, CheckCircle, XCircle, MinusCircle, FileDown, Share2 } from 'lucide-react';
import { jsPDF } from 'jspdf';

interface ResultViewProps {
  result: Result;
  studentName: string;
  questions: Question[];
  answers: Record<number, number | null>;
  onRestart: () => void;
  paperName: string;
}

const ResultView: React.FC<ResultViewProps> = ({ result, studentName, questions, answers, onRestart, paperName }) => {
  const percentage = Math.round((result.correct / result.totalQuestions) * 100);
  const isPassed = percentage >= 40;
  
  const wrongQuestions = questions.filter(q => {
    const userAns = answers[q.id];
    return userAns !== undefined && userAns !== null && userAns !== q.correctAnswer;
  });

  const downloadDMC = () => {
    const doc = new jsPDF();
    
    // Background Color Header
    doc.setFillColor(37, 99, 235); // Blue-600
    doc.rect(0, 0, 210, 60, 'F');
    
    // Header Text
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(28);
    doc.setFont('helvetica', 'bold');
    doc.text('DETAILED MARK CERTIFICATE', 105, 25, { align: 'center' });
    
    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    doc.text(`Official Academic Assessment - ${paperName}`, 105, 35, { align: 'center' });
    
    // Student Info Section
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('STUDENT INFORMATION', 20, 75);
    doc.line(20, 77, 190, 77);
    
    doc.setFont('helvetica', 'normal');
    doc.text(`Name: ${studentName}`, 20, 85);
    doc.text(`Candidate ID: 2024-${studentName.substring(0,3).toUpperCase()}`, 20, 92);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 99);
    
    // Score Summary Table
    doc.setFont('helvetica', 'bold');
    doc.text('PERFORMANCE SUMMARY', 20, 115);
    doc.line(20, 117, 190, 117);
    
    const startY = 125;
    const rowHeight = 10;
    const data = [
      ['Total MCQs', result.totalQuestions.toString()],
      ['Correct Answers', result.correct.toString()],
      ['Incorrect Answers', result.wrong.toString()],
      ['Unattempted', result.unattempted.toString()],
      ['Calculation Breakdown', `(${result.correct} * 1.0) - (${result.wrong} * 0.25)`],
      ['Total Marks Obtained', result.score.toFixed(2)],
      ['Result Status', isPassed ? 'PASS' : 'FAIL']
    ];

    data.forEach((row, i) => {
      const currentY = startY + (i * rowHeight);
      doc.setFillColor(i % 2 === 0 ? 248 : 255, i % 2 === 0 ? 250 : 255, i % 2 === 0 ? 252 : 255);
      doc.rect(20, currentY - 5, 170, rowHeight, 'F');
      
      doc.setFont('helvetica', i === data.length - 2 ? 'bold' : 'normal');
      doc.setTextColor(30, 41, 59);
      doc.text(row[0], 25, currentY + 2);
      
      if (row[1] === 'PASS') doc.setTextColor(22, 163, 74);
      if (row[1] === 'FAIL') doc.setTextColor(220, 38, 38);
      
      doc.text(row[1], 185, currentY + 2, { align: 'right' });
    });

    // Footer
    doc.setTextColor(148, 163, 184);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.text('This is an electronically generated document and does not require a physical signature.', 105, 280, { align: 'center' });
    doc.text('Generated by AceQuiz Pro Assessment Engine', 105, 285, { align: 'center' });

    doc.save(`${studentName}_DMC_${paperName}.pdf`);
  };

  const shareResult = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'My Quiz Result',
          text: `I scored ${result.score.toFixed(2)} on AceQuiz Pro ${paperName}!`,
          url: window.location.href,
        });
      } catch (err) {
        console.log('Share failed');
      }
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8 animate-in fade-in duration-700">
      <div className="bg-white rounded-3xl shadow-xl overflow-hidden border border-slate-100">
        <div className="bg-blue-600 p-8 md:p-12 text-center text-white relative">
          <div className="absolute top-4 right-4 opacity-10">
            <Trophy className="w-32 h-32" />
          </div>
          <p className="text-blue-100 font-medium mb-2 uppercase tracking-widest">{paperName} Result</p>
          <h1 className="text-4xl md:text-5xl font-extrabold mb-4">{isPassed ? 'Excellent Work,' : 'Keep Practicing,'} {studentName}!</h1>
          <div className={`inline-block px-4 py-1 rounded-full text-sm font-black mb-8 ${isPassed ? 'bg-green-500/20 text-green-200' : 'bg-red-500/20 text-red-200'}`}>
            STATUS: {isPassed ? 'PASSED' : 'FAILED'} (Min. 40% Required)
          </div>
          
          <div className="flex flex-col md:flex-row items-center justify-center gap-8">
            <div className="bg-white/10 backdrop-blur-md rounded-2xl p-6 min-w-[160px] border border-white/20">
              <p className="text-blue-200 text-sm mb-1 uppercase">Total Marks</p>
              <p className="text-5xl font-black">{result.score.toFixed(2)}</p>
              <p className="text-[10px] text-blue-300 mt-2 uppercase tracking-tighter">({result.correct}*1 - {result.wrong}*0.25)</p>
            </div>
            <div className="bg-white/10 backdrop-blur-md rounded-2xl p-6 min-w-[160px] border border-white/20">
              <p className="text-blue-200 text-sm mb-1 uppercase">Accuracy</p>
              <p className="text-5xl font-black">{percentage}%</p>
            </div>
          </div>

          <div className="mt-10 flex flex-wrap justify-center gap-4">
            <button 
              onClick={downloadDMC}
              className="bg-white text-blue-600 hover:bg-blue-50 px-6 py-3 rounded-xl font-bold flex items-center gap-2 transition-all shadow-lg active:scale-95"
            >
              <FileDown className="w-5 h-5" />
              Download DMC PDF
            </button>
            <button 
              onClick={shareResult}
              className="bg-blue-500 hover:bg-blue-400 text-white px-6 py-3 rounded-xl font-bold flex items-center gap-2 transition-all shadow-lg border border-blue-400/30 active:scale-95"
            >
              <Share2 className="w-5 h-5" />
              Share Report
            </button>
          </div>
        </div>

        <div className="p-8 grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="bg-slate-50 p-4 rounded-2xl text-center border border-slate-100">
            <CheckCircle className="w-6 h-6 text-green-500 mx-auto mb-2" />
            <p className="text-slate-500 text-xs uppercase font-bold">Correct</p>
            <p className="text-2xl font-bold text-slate-800">{result.correct}</p>
          </div>
          <div className="bg-slate-50 p-4 rounded-2xl text-center border border-slate-100">
            <XCircle className="w-6 h-6 text-red-500 mx-auto mb-2" />
            <p className="text-slate-500 text-xs uppercase font-bold">Incorrect</p>
            <p className="text-2xl font-bold text-slate-800">{result.wrong}</p>
          </div>
          <div className="bg-slate-50 p-4 rounded-2xl text-center border border-slate-100">
            <MinusCircle className="w-6 h-6 text-slate-400 mx-auto mb-2" />
            <p className="text-slate-500 text-xs uppercase font-bold">Skipped</p>
            <p className="text-2xl font-bold text-slate-800">{result.unattempted}</p>
          </div>
          <div className="bg-slate-50 p-4 rounded-2xl text-center border border-slate-100">
            <AlertCircle className="w-6 h-6 text-amber-500 mx-auto mb-2" />
            <p className="text-slate-500 text-xs uppercase font-bold">Attempted</p>
            <p className="text-2xl font-bold text-slate-800">{result.attempted}</p>
          </div>
        </div>
      </div>

      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <h2 className="text-2xl font-bold text-slate-800">Error Review</h2>
          <button 
            onClick={onRestart}
            className="flex items-center gap-2 text-blue-600 font-bold hover:underline"
          >
            <RefreshCcw className="w-4 h-4" />
            Exit to Papers
          </button>
        </div>

        {wrongQuestions.length === 0 ? (
          <div className="bg-green-50 border border-green-100 rounded-2xl p-8 text-center">
            <Trophy className="w-12 h-12 text-green-500 mx-auto mb-4" />
            <h3 className="text-xl font-bold text-green-800">Perfect Score!</h3>
            <p className="text-green-600">Legendary performance. You didn't miss a single mark.</p>
          </div>
        ) : (
          <div className="space-y-4">
            {wrongQuestions.map((q) => (
              <div key={q.id} className="bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-sm hover:border-red-200 transition-colors">
                <div className="bg-slate-50 px-6 py-3 border-b border-slate-200 flex justify-between items-center text-[10px] font-bold text-slate-400 uppercase tracking-widest">
                  <span>Question #{q.id} • {q.category}</span>
                  <span className="text-red-500 bg-red-50 px-2 py-0.5 rounded">-0.25 MARKS</span>
                </div>
                <div className="p-6">
                  <p className="text-lg font-semibold text-slate-800 mb-4">{q.question}</p>
                  <div className="grid md:grid-cols-2 gap-3">
                    <div className="p-4 rounded-xl border border-red-200 bg-red-50/50">
                      <p className="text-[10px] font-black text-red-400 uppercase mb-1">Your Selection</p>
                      <p className="text-red-700 font-medium">{q.options[answers[q.id] as number]}</p>
                    </div>
                    <div className="p-4 rounded-xl border border-green-200 bg-green-50/50">
                      <p className="text-[10px] font-black text-green-400 uppercase mb-1">Correct Answer</p>
                      <p className="text-green-700 font-medium">{q.options[q.correctAnswer]}</p>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      <div className="text-center pt-8 pb-12">
        <button
          onClick={onRestart}
          className="bg-slate-800 hover:bg-black text-white px-10 py-4 rounded-2xl font-bold flex items-center gap-3 mx-auto transition-all shadow-xl hover:-translate-y-1 active:translate-y-0"
        >
          <RefreshCcw className="w-5 h-5" />
          Back to Paper Selection
        </button>
      </div>
    </div>
  );
};

export default ResultView;
